'use client'

import { useEffect, useMemo, useState } from 'react'

const suppliers = [
  { name: 'Diamond Vintage', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/WhatsApp_Image_2023-06-01_at_12.16.32_AM.jpg?v=1685615957', categories: 'Button-up shirts · Ralph Lauren · Tommy Hilfiger · Lacoste · Trench coats', rating: '4.5', repeat: 345, dispatch: '6 days', url: 'https://www.joinfleek.com/vendor/diamond-vintage', tag: 'Branded men’s', confidence: 'High' },
  { name: 'Vintage Central', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/WhatsApp_Image_2023-03-31_at_11.00.03.jpg?v=1680267334', categories: 'Polo shirts · Lululemon', rating: '4.9', repeat: 372, dispatch: '5 days', url: 'https://www.joinfleek.com/vendor/vintage-central', tag: 'Polo / activewear', confidence: 'High' },
  { name: 'Thrift Drip', image: 'https://d345nenm7zy8g2.cloudfront.net/thrift-drip-thrift-drip.jpg', categories: 'Track pants · Nike · Adidas · Umbro', rating: '4.6', repeat: 80, dispatch: '4 days', url: 'https://www.joinfleek.com/vendor/thrift-drip', tag: 'Sportswear', confidence: 'High' },
  { name: 'Retro Fashion', image: 'https://d345nenm7zy8g2.cloudfront.net/retro-fashion-ChatGPT%20Image%20Nov%2012%2C%202025%2C%2006_12_14%20PM.png', categories: 'Puffer jackets · Retro / Y2K fashion', rating: '4.5', repeat: 56, dispatch: '3 days', url: 'https://www.joinfleek.com/vendor/retro-fashion', tag: 'Jackets', confidence: 'Medium' },
  { name: 'Thrift Kings', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/WhatsApp_Image_2023-07-06_at_2.20.25_PM.jpg?v=1688637133', categories: 'Workwear · Carhartt · Dickies', rating: '4.4', repeat: 201, dispatch: '3 days', url: 'https://www.joinfleek.com/vendor/thrift-kings', tag: 'Workwear', confidence: 'High' },
  { name: 'Asian Trader', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/WhatsApp_Image_2024-03-14_at_12.29.49.jpg?v=1710401705', categories: 'Hip-hop jeans · Japanese / Y2K denim · Carhartt · Dickies', rating: '4.5', repeat: 14, dispatch: '—', url: 'https://www.joinfleek.com/vendor/asian-trader', tag: 'Baggy denim', confidence: 'Test' },
  { name: 'Trade Vintage', image: 'https://d345nenm7zy8g2.cloudfront.net/trade-vintage-Trade%20Vintage%20Logo.png', categories: 'Denim shorts', rating: '4.6', repeat: 92, dispatch: '7 days', url: 'https://www.joinfleek.com/vendor/trade-vintage', tag: 'Denim shorts', confidence: 'High' },
  { name: 'Legacy Vintage', image: 'https://d345nenm7zy8g2.cloudfront.net/legacy-leagcy.jpg', categories: 'Miniskirts · Y2K denim · Hip-hop / baggy jorts', rating: '4.8', repeat: 63, dispatch: '6 days', url: 'https://www.joinfleek.com/vendor/legacy', tag: 'Y2K denim', confidence: 'High' },
  { name: 'Vintage Master', image: 'https://d345nenm7zy8g2.cloudfront.net/mohsin-fashion-bazar-7rfv5hRniRljm1NfVR22VdDi.jpeg', categories: 'Denim skirts', rating: '5.0', repeat: 77, dispatch: '3 days', url: 'https://www.joinfleek.com/vendor/mohsin-fashion-bazar', tag: 'Denim skirts', confidence: 'High' },
  { name: 'The Ethereal Wardrobe', image: 'https://d345nenm7zy8g2.cloudfront.net/ethereal-WhatsApp%20Image%202024-03-19%20at%2012.40.08.jpeg', categories: 'Cami tops · Nike · Y2K', rating: '4.8', repeat: 222, dispatch: '2 days', url: 'https://www.joinfleek.com/vendor/ethereal', tag: 'Y2K / Nike', confidence: 'High' },
  { name: 'Retro Thrift Store', image: 'https://d345nenm7zy8g2.cloudfront.net/retro-thrift-store-1-WhatsApp%20Image%202026-04-29%20at%2017.54.06.jpeg', categories: 'General Y2K · Coach bags', rating: '4.7', repeat: 478, dispatch: '3 days', url: 'https://www.joinfleek.com/vendor/retro-thrift-store-1', tag: 'Y2K / bags', confidence: 'High' },
  { name: 'MH Vintage', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/WhatsApp_Image_2023-05-16_at_22.34.37_a9d51126-4cdc-4d0a-9c63-0c157b82b97a.jpg?v=1684258680', categories: 'Single-stitch T-shirts', rating: '4.7', repeat: 273, dispatch: '4 days', url: 'https://www.joinfleek.com/vendor/mh-vintage-2', tag: 'Vintage tees', confidence: 'High' },
  { name: 'Vintage Visions', image: 'https://d345nenm7zy8g2.cloudfront.net/vintage-visions-clotting%20logo-02.jpg', categories: 'Vintage band tees', rating: '4.8', repeat: 173, dispatch: '2 days', url: 'https://www.joinfleek.com/vendor/vintage-visions', tag: 'Band tees', confidence: 'High' },
  { name: 'Vintage Storm', image: 'https://d345nenm7zy8g2.cloudfront.net/vintage-storm-FA.jpeg', categories: 'Ralph Lauren · branded vintage', rating: '4.6', repeat: 514, dispatch: '7 days', url: 'https://www.joinfleek.com/vendor/vintage-storm', tag: 'Ralph Lauren', confidence: 'High' },
  { name: 'Creed Vintage', image: 'https://cdn.shopify.com/s/files/1/0610/8233/7518/files/fleekLogoBlack.png?v=1698234330', categories: 'Miss Me · True Religion · Rock Revival · Y2K denim', rating: '4.8', repeat: 1379, dispatch: '4 days', url: 'https://www.joinfleek.com/vendor/creed-vintage', tag: 'Premium Y2K denim', confidence: 'Very high' },
]
const sourcingTabs = ['All', 'Branded men’s', 'Y2K', 'Denim', 'Tees', 'Workwear', 'Sportswear']
const today = () => new Date().toISOString().slice(0, 10)
const blankPurchase = { source_type: 'Fleek', order_number: '', description: '', total_cost: '', order_date: today(), expected_delivery_date: '' }

export default function Home() {
  const [tab, setTab] = useState('Overview')
  const [sourceTab, setSourceTab] = useState('All')
  const [products, setProducts] = useState<any[]>([])
  const [balances, setBalances] = useState<any[]>([])
  const [purchases, setPurchases] = useState<any[]>([])
  const [purchaseItems, setPurchaseItems] = useState<any[]>([])
  const [showPurchase, setShowPurchase] = useState(false)
  const [receivePurchase, setReceivePurchase] = useState<any | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [purchaseForm, setPurchaseForm] = useState(blankPurchase)
  const [receiveDate, setReceiveDate] = useState(today())
  const [items, setItems] = useState<any[]>([{ description: '', grade: '', brand: '', size: '', condition: '', unit_cost: '', listed_price: '', projected_profit_ebay: '', projected_profit_depop: '', projected_profit_shopify: '', listing_date: '' }])
  const nav = ['Overview', 'Inventory', 'Orders', 'Sourcing', 'Bookkeeping', 'Automation', 'Settings']

  async function loadData() {
    try { const r = await fetch('/api/inventory', { cache: 'no-store' }); if (!r.ok) return; const d = await r.json(); setProducts(d.products || []); setBalances(d.balances || []); setPurchases(d.purchases || []); setPurchaseItems(d.purchase_items || []) } catch {}
  }
  useEffect(() => { loadData() }, [])
  useEffect(() => { window.scrollTo(0, 0) }, [tab, sourceTab])
  const visibleSuppliers = useMemo(() => suppliers.filter(s => sourceTab === 'All' || s.tag.toLowerCase().includes(sourceTab.toLowerCase().replace('branded men’s', 'branded')) || s.categories.toLowerCase().includes(sourceTab.toLowerCase().replace('branded men’s', 'branded'))), [sourceTab])
  const close = () => { if (!saving) { setShowPurchase(false); setReceivePurchase(null); setError('') } }
  const setPurchaseField = (k: string, v: string) => setPurchaseForm(f => ({ ...f, [k]: v }))
  const setItem = (i: number, k: string, v: string) => setItems(a => a.map((x, n) => n === i ? { ...x, [k]: v } : x))
  const addItemRow = () => setItems(a => [...a, { description: '', grade: '', brand: '', size: '', condition: '', unit_cost: '', listed_price: '', projected_profit_ebay: '', projected_profit_depop: '', projected_profit_shopify: '', listing_date: '' }])

  async function createPurchase(e: React.FormEvent) {
    e.preventDefault(); setSaving(true); setError('')
    try { const r = await fetch('/api/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'create_purchase', ...purchaseForm, total_cost: Number(purchaseForm.total_cost), order_date: new Date(purchaseForm.order_date).toISOString(), expected_delivery_date: purchaseForm.expected_delivery_date ? new Date(purchaseForm.expected_delivery_date).toISOString() : null }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Could not create purchase'); setShowPurchase(false); setPurchaseForm(blankPurchase); await loadData() } catch (e: any) { setError(e.message) } finally { setSaving(false) }
  }

  async function receive(e: React.FormEvent) {
    e.preventDefault(); setSaving(true); setError('')
    try { const valid = items.filter(x => x.description.trim()); if (!valid.length) throw new Error('Add at least one item'); const r = await fetch('/api/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'receive_purchase', purchase_id: receivePurchase.id, delivered_at: new Date(receiveDate).toISOString(), items: valid }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Could not receive purchase'); setReceivePurchase(null); setItems([{ description: '', grade: '', brand: '', size: '', condition: '', unit_cost: '', listed_price: '', projected_profit_ebay: '', projected_profit_depop: '', projected_profit_shopify: '', listing_date: '' }]); await loadData() } catch (e: any) { setError(e.message) } finally { setSaving(false) }
  }

  return <div className="shell">
    <aside className="sidebar"><div className="brand">ALBA VINTAGE</div><div className="sub">commerce control centre</div><nav className="nav">{nav.map(n => <button key={n} className={tab === n ? 'active' : ''} onClick={() => setTab(n)}>{n}</button>)}</nav><div className="note" style={{ marginTop: 30 }}>Database: <strong>Supabase</strong><br/>Automation: <strong>n8n</strong></div></aside>
    <main className="main">
      <div className="top"><div><div className="eyebrow">Alba Vintage</div><div className="title">{tab}</div><div className="muted">One inventory. Multiple channels. Your data.</div></div><div className="status"><span className="dot"/> System healthy</div></div>
      {tab === 'Overview' && <div className="grid"><div className="card"><div className="label">Available stock</div><div className="metric">{balances.reduce((n,x)=>n+Number(x.available_quantity||0),0)}</div></div><div className="card"><div className="label">Stock lines</div><div className="metric">{products.length}</div></div><div className="card"><div className="label">Purchases awaiting delivery</div><div className="metric">{purchases.filter(p=>p.status==='ordered').length}</div></div><div className="card"><div className="label">Inventory model</div><div className="metric">Movement</div></div><div className="section wide"><div className="card"><h2>Purchase → receive → inventory</h2><p className="muted">Log a Fleek or Shop order when you place it. Nothing enters inventory until the parcel arrives and you receive its individual items.</p><button className="btn" onClick={()=>{setTab('Orders');setShowPurchase(true)}}>+ Log purchase</button></div></div></div>}

      {tab === 'Inventory' && <div className="inventory-page"><div className="inventory-actions"><div><h2>Master inventory</h2><p className="muted">Only physically received stock appears here. Each received item has its own database row.</p></div><button className="btn" onClick={()=>setTab('Orders')}>View purchases</button></div><div className="card"><table className="table"><thead><tr><th>SKU</th><th>Description</th><th>Grade</th><th>Cost</th><th>Listed</th><th>Entered</th><th>Sale date</th></tr></thead><tbody>{products.length ? products.map(p=><tr key={p.id}><td className="sku">{p.sku}</td><td>{p.title}</td><td>{p.grade||'—'}</td><td>£{Number(p.purchase_cost||0).toFixed(2)}</td><td>£{Number(p.listed_price||0).toFixed(2)}</td><td>{p.stock_entered_at?new Date(p.stock_entered_at).toLocaleDateString('en-GB'):'—'}</td><td>{p.sale_date?new Date(p.sale_date).toLocaleDateString('en-GB'):'—'}</td></tr>) : <tr><td colSpan={7}><div className="empty">No stock received yet. Log a purchase first, then receive it when it arrives.</div></td></tr>}</tbody></table></div></div>}

      {tab === 'Orders' && <div className="orders-page"><div className="inventory-actions"><div><h2>Purchases</h2><p className="muted">Record the order immediately. Receiving it later creates the actual inventory rows.</p></div><button className="btn" onClick={()=>setShowPurchase(true)}>+ Log purchase</button></div><div className="card"><table className="table"><thead><tr><th>Supplier</th><th>Order</th><th>Description</th><th>Order date</th><th>Expected</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{purchases.length?purchases.map(p=><tr key={p.id}><td>{p.supplier_id?'Supplier':'Fleek / Shop'}</td><td className="sku">{p.reference||'—'}</td><td>{p.notes||'—'}</td><td>{new Date(p.order_date||p.purchased_at).toLocaleDateString('en-GB')}</td><td>{p.expected_delivery_date?new Date(p.expected_delivery_date).toLocaleDateString('en-GB'):'—'}</td><td>£{Number(p.total_cost||0).toFixed(2)}</td><td><span className="pill">{p.status==='received'?'Delivered':'Awaiting delivery'}</span></td><td>{p.status!=='received'&&<button className="btn small" onClick={()=>{setReceivePurchase(p);setReceiveDate(today());setError('')}}>Receive</button>}</td></tr>):<tr><td colSpan={8}><div className="empty">No purchases logged yet.</div></td></tr>}</tbody></table></div></div>}

      {tab === 'Sourcing' && <div className="sourcing"><div className="sourcing-head card"><div><div className="label">FLEEK SUPPLIER INTELLIGENCE</div><h2>Wholesale sourcing desk</h2><p className="muted">Research-backed shortlist from Fleek supplier data. Use the category tabs to narrow the field, then open the supplier directly.</p></div><div className="sourcing-stats"><div><strong>{suppliers.length}</strong><span>suppliers</span></div><div><strong>{suppliers.filter(s=>s.confidence==='High'||s.confidence==='Very high').length}</strong><span>strong candidates</span></div><div><strong>PK</strong><span>source market</span></div></div></div><div className="source-tabs">{sourcingTabs.map(t=><button key={t} className={sourceTab===t?'active':''} onClick={()=>setSourceTab(t)}>{t}</button>)}</div><div className="supplier-grid">{visibleSuppliers.map(s=><article className="supplier card" key={s.name}><div className="supplier-image-wrap"><img className="supplier-image" src={s.image} alt={`${s.name} logo`} loading="lazy" /></div><div className="supplier-top"><span className="supplier-tag">{s.tag}</span><span className={`confidence ${s.confidence.toLowerCase().replace(' ','-')}`}>{s.confidence}</span></div><h3>{s.name}</h3><p className="supplier-cat">{s.categories}</p><div className="supplier-metrics"><div><strong>{s.rating}★</strong><span>rating</span></div><div><strong>{s.repeat}+</strong><span>repeat buyers</span></div><div><strong>{s.dispatch}</strong><span>dispatch</span></div></div><a className="supplier-link" href={s.url} target="_blank" rel="noreferrer">Open supplier ↗</a></article>)}</div></div>}
      {tab === 'Bookkeeping' && <div className="card"><h2>Bookkeeping</h2><p className="muted">Completed sales will become the source of truth for revenue, fees, postage, cost, profit and sale dates.</p></div>}
      {tab === 'Automation' && <div className="card"><h2>n8n automation</h2><p className="muted">Sale → idempotency check → mark SKU sold → delist other channels → retry failures → reconcile.</p></div>}
      {tab === 'Settings' && <div className="settings"><div className="card wide"><h2>Integration settings</h2><div className="note">Credentials should never be stored in browser code. Production flow: UI → authenticated server endpoint → secret store / n8n credentials.</div></div>{['n8n base URL','Shopify store','eBay account','Depop account','Google Sheets spreadsheet ID'].map((x,i)=><div className="card field" key={x}><label>{x}</label><input type={i===0?'url':'text'} placeholder={i===0?'https://n8n.example.com':'Not configured'} /></div>)}</div>}
    </main>

    {showPurchase&&<div className="modal-backdrop" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">Purchasing</div><h2>Log purchase</h2><p className="muted">Record the order now. Inventory stays unchanged until delivery.</p></div><button className="modal-close" onClick={close}>×</button></div><form onSubmit={createPurchase} className="stock-form"><div className="form-grid"><div className="field"><label>Source</label><select value={purchaseForm.source_type} onChange={e=>setPurchaseField('source_type',e.target.value)}><option>Fleek</option><option>Shop</option></select></div><div className="field"><label>Fleek / Shop order number</label><input required value={purchaseForm.order_number} onChange={e=>setPurchaseField('order_number',e.target.value)} placeholder="e.g. FLK-12345" /></div></div><div className="field"><label>Description</label><input required value={purchaseForm.description} onChange={e=>setPurchaseField('description',e.target.value)} placeholder="e.g. 20-piece branded tee bundle" /></div><div className="form-grid three"><div className="field"><label>Total order cost (£)</label><input required type="number" min="0" step="0.01" value={purchaseForm.total_cost} onChange={e=>setPurchaseField('total_cost',e.target.value)} /></div><div className="field"><label>Order date</label><input required type="date" value={purchaseForm.order_date} onChange={e=>setPurchaseField('order_date',e.target.value)} /></div><div className="field"><label>Expected delivery</label><input type="date" value={purchaseForm.expected_delivery_date} onChange={e=>setPurchaseField('expected_delivery_date',e.target.value)} /></div></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn" disabled={saving}>{saving?'Saving…':'Log purchase'}</button></div></form></div></div>}

    {receivePurchase&&<div className="modal-backdrop" onMouseDown={close}><div className="modal modal-wide" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">Goods received</div><h2>Receive {receivePurchase.reference}</h2><p className="muted">Enter one row per actual item. Each row becomes its own product/inventory record.</p></div><button className="modal-close" onClick={close}>×</button></div><form onSubmit={receive} className="stock-form"><div className="form-grid"><div className="field"><label>Delivered date</label><input required type="date" value={receiveDate} onChange={e=>setReceiveDate(e.target.value)} /></div><div className="field"><label>Items received</label><input disabled value={items.filter(x=>x.description.trim()).length} /></div></div><div className="receive-table"><div className="receive-row receive-head"><span>Description</span><span>Grade</span><span>Brand</span><span>Size</span><span>Condition</span><span>Unit cost</span><span>Listed</span></div>{items.map((it,i)=><div className="receive-row" key={i}><input required placeholder="Nike T-shirt" value={it.description} onChange={e=>setItem(i,'description',e.target.value)}/><input placeholder="A" value={it.grade} onChange={e=>setItem(i,'grade',e.target.value)}/><input placeholder="Nike" value={it.brand} onChange={e=>setItem(i,'brand',e.target.value)}/><input placeholder="L" value={it.size} onChange={e=>setItem(i,'size',e.target.value)}/><input placeholder="Good" value={it.condition} onChange={e=>setItem(i,'condition',e.target.value)}/><input type="number" step="0.01" placeholder="8.00" value={it.unit_cost} onChange={e=>setItem(i,'unit_cost',e.target.value)}/><input type="number" step="0.01" placeholder="29.99" value={it.listed_price} onChange={e=>setItem(i,'listed_price',e.target.value)}/></div>)}</div><button type="button" className="btn secondary" onClick={addItemRow}>+ Add another item</button><div className="form-grid three"><div className="field"><label>Projected eBay profit (£)</label><input type="number" step="0.01" placeholder="Optional per item" /></div><div className="field"><label>Projected Depop profit (£)</label><input type="number" step="0.01" placeholder="Optional per item" /></div><div className="field"><label>Projected Shopify profit (£)</label><input type="number" step="0.01" placeholder="Optional per item" /></div></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn secondary" onClick={close}>Cancel</button><button className="btn" disabled={saving}>{saving?'Receiving…':'Receive stock'}</button></div></form></div></div>}
  </div>
}
